.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LIBNFO-READER 1 "09/12/2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
libnfo-reader \- an utility to read NFO files  which uses libnfo
.SH SYNOPSIS
\fBlibnfo-reader\fP <\fIfile\fP>
.SH DESCRIPTION
This manual page documents briefly the \fBlibnfo-reader\fP command.
.PP
\fBlibnfo-reader\fP parses an NFO file and outputs its contents to
the standard output.
.SH OPTIONS
none
.SH AUTHOR
libnfo was written by Benjamin Zores <ben@geexbox.org>.
.PP
This manual page was written by Davide Cavalca <davide@geexbox.org>,
for the Debian project (but may be used by others).
